const { db } = require('./connection');
const { hashPassword } = require('../security');
const { encryptText, decryptText } = require('../privacy');

function value(item, key, fallback = '') { return item[key] ?? item[key.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`)] ?? fallback; }
function insertUser(item) { db.prepare('INSERT OR IGNORE INTO users (account,name,role,campus,active,protected,password_hash,created_at) VALUES (?,?,?,?,?,?,?,?)').run(value(item, 'account'), value(item, 'name'), value(item, 'role', 'technician'), value(item, 'campus', '南湖 / 浑南'), value(item, 'active', true) ? 1 : 0, value(item, 'protected', false) ? 1 : 0, value(item, 'passwordHash') || (value(item, 'password') ? hashPassword(value(item, 'password')) : null), value(item, 'createdAt', new Date().toISOString().slice(0, 10))); }
function insertAppointment(item) { db.prepare(`INSERT OR IGNORE INTO appointments (id,student_id,name,college,campus,phone,social,device_type,brand,device_model,serial,warranty,fault_type,issue,liquid_drop,date,time_slot,note,status,assigned_to,repair_note,created_at,agreement_at,agreement_version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(value(item, 'id'), value(item, 'studentId'), value(item, 'name'), value(item, 'college'), value(item, 'campus', '南湖'), encryptText(value(item, 'phone')), encryptText(value(item, 'social')), value(item, 'deviceType'), value(item, 'brand'), value(item, 'deviceModel'), value(item, 'serial'), value(item, 'warranty'), value(item, 'faultType', '其他'), value(item, 'issue'), value(item, 'liquidDrop'), value(item, 'date'), value(item, 'timeSlot'), value(item, 'note'), value(item, 'status', 'pending'), value(item, 'assignedTo'), value(item, 'repairNote'), value(item, 'createdAt', new Date().toISOString()), value(item, 'agreementAt'), value(item, 'agreementVersion', 'v1.0')); }

function appointmentRow(row) { return { id: row.id, studentId: row.student_id, name: row.name, college: row.college, campus: row.campus, phone: decryptText(row.phone), social: decryptText(row.social), deviceType: row.device_type, brand: row.brand, deviceModel: row.device_model, serial: row.serial, warranty: row.warranty, faultType: row.fault_type, issue: row.issue, liquidDrop: row.liquid_drop, date: row.date, timeSlot: row.time_slot, note: row.note, status: row.status, assignedTo: row.assigned_to, repairNote: row.repair_note, createdAt: row.created_at, agreementAt: row.agreement_at, agreementVersion: row.agreement_version }; }
function userRow(row) { return { account: row.account, name: row.name, role: row.role, campus: row.campus, active: Boolean(row.active), protected: Boolean(row.protected), createdAt: row.created_at }; }
function userAuthRow(row) { return row ? { ...userRow(row), passwordHash: row.password_hash, tokenVersion: row.token_version || 0 } : null; }

function listAppointments() { return db.prepare('SELECT * FROM appointments ORDER BY created_at DESC').all().map(appointmentRow); }
function listUsers() { return db.prepare('SELECT * FROM users ORDER BY role DESC, name').all().map(userRow); }
function findUser(account) { const row = db.prepare('SELECT * FROM users WHERE account = ?').get(account); return row ? userRow(row) : null; }
function findUserAuth(account) { return userAuthRow(db.prepare('SELECT * FROM users WHERE account = ?').get(account)); }
function createUser(item) { insertUser(item); return findUser(item.account); }
function updateUser(account, patch) { const fields = []; const params = []; for (const [key, column] of [['role', 'role'], ['active', 'active'], ['name', 'name'], ['campus', 'campus'], ['passwordHash', 'password_hash']]) { if (patch[key] !== undefined) { fields.push(`${column} = ?`); params.push(key === 'active' ? (patch[key] ? 1 : 0) : patch[key]); } } if (patch.passwordHash !== undefined || patch.active !== undefined) fields.push('token_version = token_version + 1'); if (fields.length) db.prepare(`UPDATE users SET ${fields.join(', ')} WHERE account = ? AND protected = 0`).run(...params, account); return findUser(account); }
function setPassword(account, password) { db.prepare('UPDATE users SET password_hash = ? WHERE account = ?').run(hashPassword(password), account); return findUser(account); }
function deleteUser(account) { const result = db.prepare('DELETE FROM users WHERE account = ? AND protected = 0').run(account); return result.changes > 0; }
function revokeUserTokens(account) { db.prepare('UPDATE users SET token_version = token_version + 1 WHERE account = ?').run(account); return findUserAuth(account); }
function createAppointment(item, options = {}) {
  const capacity = Number(options.capacity || 5);
  const campusCode = item.campus === '浑南' ? '1' : '0';
  db.exec('BEGIN IMMEDIATE');
  try {
    const duplicate = db.prepare("SELECT 1 AS found FROM appointments WHERE student_id = ? AND date = ? AND time_slot = ? AND status NOT IN ('cancelled', 'no_show') LIMIT 1").get(item.studentId, item.date, item.timeSlot);
    if (duplicate) throw Object.assign(new Error('同一时段已经存在预约'), { code: 'DUPLICATE_APPOINTMENT' });
    const used = db.prepare("SELECT COUNT(*) AS count FROM appointments WHERE campus = ? AND date = ? AND time_slot = ? AND status NOT IN ('cancelled', 'no_show')").get(item.campus, item.date, item.timeSlot).count;
    if (used >= capacity) throw Object.assign(new Error('该校区该时段已满'), { code: 'SLOT_FULL' });
    const next = db.prepare("SELECT COALESCE(MAX(CAST(substr(id, instr(id, '-') + 1) AS INTEGER)), 0) + 1 AS next FROM appointments WHERE campus = ? AND date = ?").get(item.campus, item.date).next;
    const id = `${campusCode}${String(item.date).replaceAll('-', '')}-${String(next).padStart(2, '0')}`;
    insertAppointment({ ...item, id, status: 'pending', createdAt: new Date().toISOString(), agreementVersion: item.agreementVersion || 'v1.0' });
    db.exec('COMMIT');
    return getAppointment(id);
  } catch (error) {
    try { db.exec('ROLLBACK'); } catch { /* Preserve the original database error. */ }
    throw error;
  }
}
function getAppointment(id) { const row = db.prepare('SELECT * FROM appointments WHERE id = ?').get(id); return row ? appointmentRow(row) : null; }
function addAttachment(item) { db.prepare('INSERT INTO appointment_attachments (id,appointment_id,filename,mime_type,size,storage_path,created_at) VALUES (?,?,?,?,?,?,?)').run(item.id, item.appointmentId, item.filename, item.mimeType, item.size, item.storagePath, item.createdAt || new Date().toISOString()); return attachmentRow(db.prepare('SELECT * FROM appointment_attachments WHERE id = ?').get(item.id)); }
function attachmentRow(row) { return { id: row.id, appointmentId: row.appointment_id, filename: row.filename, mimeType: row.mime_type, size: row.size, createdAt: row.created_at }; }
function listAttachments(appointmentId) { return db.prepare('SELECT * FROM appointment_attachments WHERE appointment_id = ? ORDER BY created_at').all(appointmentId).map(attachmentRow); }
function getAttachment(id) { const row = db.prepare('SELECT * FROM appointment_attachments WHERE id = ?').get(id); return row ? { ...attachmentRow(row), storagePath: row.storage_path } : null; }
function updateAppointment(id, patch) { const map = { status: 'status', assignedTo: 'assigned_to', repairNote: 'repair_note' }; const fields = []; const params = []; for (const [key, column] of Object.entries(map)) if (patch[key] !== undefined) { fields.push(`${column} = ?`); params.push(patch[key]); } if (fields.length) db.prepare(`UPDATE appointments SET ${fields.join(', ')} WHERE id = ?`).run(...params, id); return getAppointment(id); }
function makeStats(items, range, day) { const start = day ? '' : (range && range !== 'all' ? new Date(Date.now() - (Number(range) - 1) * 86400000).toISOString().slice(0, 10) : ''); const rows = items.filter(item => (!start || item.date >= start) && (!day || item.date === day)); const daily = {}; const faults = {}; const campuses = {}; const technicians = {}; rows.forEach(item => { daily[item.date] = daily[item.date] || { total: 0, completed: 0 }; daily[item.date].total += 1; if (item.status === 'completed') { daily[item.date].completed += 1; faults[item.faultType || '未分类'] = (faults[item.faultType || '未分类'] || 0) + 1; } campuses[item.campus || '未填写'] = (campuses[item.campus || '未填写'] || 0) + 1; if (item.assignedTo) { technicians[item.assignedTo] = technicians[item.assignedTo] || { claimed: 0, completed: 0 }; technicians[item.assignedTo].claimed += 1; if (item.status === 'completed') technicians[item.assignedTo].completed += 1; } }); const completed = rows.filter(item => item.status === 'completed').length; const noShow = rows.filter(item => item.status === 'no_show').length; return { range: range || 'all', day: day || '', total: rows.length, completed, completionRate: rows.length ? Math.round(completed / rows.length * 100) : 0, noShow, noShowRate: rows.length ? Math.round(noShow / rows.length * 100) : 0, daily, faults, campuses, technicians }; }
function liveSummary(items, query) { const date = query.date || new Date().toISOString().slice(0, 10); const active = item => !['cancelled', 'no_show'].includes(item.status); const dayRows = items.filter(item => item.date === date && active(item)); const campusRows = query.campus ? dayRows.filter(item => item.campus === query.campus) : dayRows; const slotRows = query.timeSlot ? campusRows.filter(item => item.timeSlot === query.timeSlot) : campusRows; const current = query.appointmentId ? items.find(item => item.id === query.appointmentId) : null; const queue = current ? items.filter(item => item.date === current.date && item.campus === current.campus && item.timeSlot === current.timeSlot && active(item)).sort((a, b) => String(a.createdAt || a.id).localeCompare(String(b.createdAt || b.id))) : slotRows.slice().sort((a, b) => String(a.createdAt || a.id).localeCompare(String(b.createdAt || b.id))); const index = current ? queue.findIndex(item => item.id === current.id) : -1; return { date, dayTotal: dayRows.length, campusDayTotal: campusRows.length, slotTotal: slotRows.length, ahead: index >= 0 ? index : null, position: index >= 0 ? index + 1 : null, queueTotal: queue.length }; }

module.exports = { db, insertUser, insertAppointment, listAppointments, listUsers, findUser, findUserAuth, createUser, updateUser, setPassword, deleteUser, revokeUserTokens, createAppointment, getAppointment, updateAppointment, addAttachment, listAttachments, getAttachment, makeStats, liveSummary };
