import { initNavigation } from '/shared/navigation.js';
import { initBooking } from './booking.js';
import { initLookup } from './lookup.js';
const appointments=[];
let importing=false,switchView;
const lookup=initLookup(appointments,{onPrivateLink:()=>{importing=true;switchView?.('lookup');importing=false;}});
importing=lookup.hasPrivateLink;
switchView=initNavigation(view=>{if(view==='lookup' && !importing)lookup.refresh();});
initBooking({appointments});
if(lookup.hasPrivateLink) switchView('lookup');
importing=false;
