import { $, showToast, localDateString, apiFetch } from './utils.js';
import { saveAppointments } from './store.js';

const SLOT_CAPACITY = 20;
function isServiceDay(date) { const day = date.getDay(); return day >= 1 && day <= 4; }
function canonicalTimeSlot(value) { const match = String(value || '').match(/(\d{1,2}):(\d{2})[^0-9]+(\d{1,2}):(\d{2})/); if (!match) return ''; const key = `${match[1].padStart(2, '0')}:${match[2]}-${match[3].padStart(2, '0')}:${match[4]}`; return { '19:00-20:00': '19:00–20:00', '20:00-21:00': '20:00–21:00' }[key] || ''; }
function firstServiceDate(start) { const date = new Date(start); for (let i = 0; i <= 3; i += 1) { const candidate = new Date(date); candidate.setDate(date.getDate() + i); if (isServiceDay(candidate)) return candidate; } return date; }
function configureDateRange() { const input = $('input[name="date"]'); const start = new Date(); const end = new Date(start); end.setDate(end.getDate() + 3); input.min = localDateString(start); input.max = localDateString(end); input.value = localDateString(firstServiceDate(start)); }
function localLiveSummary(appointments, campus, date, timeSlot) { const active = item => !['cancelled', 'no_show'].includes(item.status); const dayRows = appointments.filter(item => item.date === date && item.campus === campus && active(item)); return { campusDayTotal: dayRows.length, slotTotal: dayRows.filter(item => item.timeSlot === timeSlot).length }; }
function fileData(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = reject; reader.readAsDataURL(file); }); }
async function uploadAttachments(appointment, files) { for (const file of files) { const data = await fileData(file); const response = await apiFetch(`/api/appointments/${encodeURIComponent(appointment.id)}/attachments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ studentId: appointment.studentId, filename: file.name, mimeType: file.type, data }) }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || '附件上传失败'); } } }

function updateCapacity(appointments) { const campus = $('select[name="campus"]').value; const date = $('input[name="date"]').value; const select = $('select[name="timeSlot"]'); const hint = $('#slot-capacity'); if (!campus || !date) { hint.textContent = '请选择校区和日期查看剩余名额'; return; } if (!isServiceDay(new Date(`${date}T12:00:00`))) { hint.textContent = '服务时间为周一至周四，请选择工作日'; select.value = ''; return; } [...select.options].forEach(option => { if (!option.value) return; const label = option.dataset.baseLabel || option.value; option.dataset.baseLabel = label; const used = appointments.filter(item => item.campus === campus && item.date === date && item.timeSlot === label && !['cancelled', 'no_show'].includes(item.status)).length; option.disabled = used >= SLOT_CAPACITY; option.textContent = label + (option.disabled ? ' · 已满' : ` · 剩余 ${SLOT_CAPACITY - used} 名`); }); if (select.selectedOptions[0]?.disabled) select.value = ''; const selected = select.value; const used = selected ? appointments.filter(item => item.campus === campus && item.date === date && item.timeSlot === selected && !['cancelled', 'no_show'].includes(item.status)).length : 0; hint.textContent = selected ? `该校区该时段还可预约 ${SLOT_CAPACITY - used} 人` : '每个校区每个时段最多 20 人'; }

async function updateLiveSummary(appointments) {
  const campus = $('select[name="campus"]').value; const date = $('input[name="date"]').value; const timeSlot = $('select[name="timeSlot"]').value;
  if (!campus || !date) { $('#live-day-count').textContent = '—'; $('#live-campus-count').textContent = '—'; $('#live-slot-count').textContent = '—'; $('#live-day-label').textContent = '请选择校区'; $('#live-campus-label').textContent = '请选择校区和时段'; $('#live-updated').textContent = '等待选择校区'; return; }
  let summary = localLiveSummary(appointments, campus, date, timeSlot);
  try { const query = new URLSearchParams({ date, campus, timeSlot }); const response = await apiFetch(`/api/live/summary?${query}`); if (response.ok) summary = await response.json(); } catch { /* Keep the last local value if the server is temporarily unavailable. */ }
  $('#live-day-count').textContent = summary.campusDayTotal; $('#live-campus-count').textContent = timeSlot ? summary.slotTotal : '—'; $('#live-slot-count').textContent = timeSlot ? Math.max(0, SLOT_CAPACITY - summary.slotTotal) : '—'; $('#live-day-label').textContent = `${campus} · ${date}`; $('#live-campus-label').textContent = timeSlot ? `${campus} · ${timeSlot}` : '请选择时段'; $('#live-updated').textContent = `刚刚更新 · ${new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}`;
}

export function initBooking({ appointments, onCreated }) {
  const form = $('#booking-form'); configureDateRange();
  ['campus', 'timeSlot'].forEach(name => $(`[name="${name}"]`).addEventListener('change', () => { updateCapacity(appointments); updateLiveSummary(appointments); }));
  $('[name="date"]').addEventListener('change', event => { const value = event.currentTarget.value; if (value && !isServiceDay(new Date(`${value}T12:00:00`))) { event.currentTarget.value = ''; showToast('可预约日期仅限周一至周四'); } updateCapacity(appointments); updateLiveSummary(appointments); });
  updateCapacity(appointments); updateLiveSummary(appointments);
  const liveTimer = setInterval(() => { updateCapacity(appointments); updateLiveSummary(appointments); }, 10000); window.addEventListener('beforeunload', () => clearInterval(liveTimer));
  $('#agreement-link').addEventListener('click', event => { event.preventDefault(); $('#agreement-modal').hidden = false; });
  $('#close-agreement').addEventListener('click', () => $('#agreement-modal').hidden = true);
  $('#agree-modal').addEventListener('click', () => { $('#agreement-modal').hidden = true; $('[name="agreement"]').checked = true; });
  $('#agreement-modal').addEventListener('click', event => { if (event.target.id === 'agreement-modal') $('#agreement-modal').hidden = true; });
  $('#new-booking').addEventListener('click', () => { form.reset(); configureDateRange(); updateCapacity(appointments); updateLiveSummary(appointments); form.hidden = false; $('.section-heading').hidden = false; $('#success-panel').hidden = true; });
  $('#copy-code').addEventListener('click', async () => { try { await navigator.clipboard.writeText($('#success-code').textContent); showToast('预约编号已复制'); } catch { showToast('请手动记录预约编号'); } });
  form.addEventListener('submit', async event => { event.preventDefault(); if (!form.checkValidity()) { form.reportValidity(); return; } const data = Object.fromEntries(new FormData(form).entries()); data.timeSlot = canonicalTimeSlot(data.timeSlot); const files = [...($('#appointment-attachments')?.files || [])]; if (files.some(file => file.size > 5 * 1024 * 1024)) { showToast('单个附件不能超过 5 MB'); return; } const appointmentDate = new Date(`${data.date}T12:00:00`); const used = appointments.filter(item => item.campus === data.campus && item.date === data.date && item.timeSlot === data.timeSlot && !['cancelled', 'no_show'].includes(item.status)).length; if (!isServiceDay(appointmentDate)) { showToast('服务时间为周一至周四'); return; } if (!data.timeSlot) { showToast('请选择 19:00–20:00 或 20:00–21:00'); return; } if (used >= SLOT_CAPACITY) { showToast('该校区该时段已满，请选择其他时段'); updateCapacity(appointments); return; } const payload = { ...data, agreementAt: new Date().toISOString(), agreementVersion: 'v1.0' }; delete payload.agreement; try { const response = await apiFetch('/api/appointments', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) { const body = await response.json().catch(() => ({})); showToast(body.error || '预约提交失败，请稍后重试'); return; } const appointment = await response.json(); if (files.length) { try { await uploadAttachments(appointment, files); } catch (error) { showToast(`预约已提交，但${error.message}`); } } appointments.unshift(appointment); saveAppointments(appointments); $('#success-code').textContent = appointment.id; $('#success-summary').textContent = `${appointment.campus} · ${appointment.date} · ${appointment.timeSlot}`; form.hidden = true; $('.section-heading').hidden = true; $('#success-panel').hidden = false; if (!files.length) showToast('免费维修预约已提交'); onCreated?.(appointment); } catch { showToast('无法连接服务器，预约未提交'); } });
}
